on: [push]
jobs:
  BuildPDF:
    runs-on: ubuntu-20.04
    name: A job to build PDF from .tex
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build PDF file
        uses: ./
